services:
  app:
    image: markokaseke/pipelinedemo:1.0.0
    container_name: pipelinedemo-container-1
    restart: unless-stopped        
      
    ports:
      - "8081:8081"
    networks:
      - pipelinedemo-net

networks:
  pipelinedemo-net:
    driver: bridge
